- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - ./vars.yml    
  tasks:
  #copia request a carpeta temporal del contenedor
  - template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    with_items:
    - { src:  request_gr1.xml , dest: "{{requestfile1}}" }
    - { src:  request_gr2.xml, dest: "{{requestfile2}}" }
    
  - command: "date +'%Y-%m-%d' -d '-1 days'"
    register: fecha
  - name: Replace fecha
    replace:
      path: "{{item}}"
      regexp: '[12]\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])'
      replace: '{{fecha.stdout}}'
    with_items:
    - "{{requestfile1}}"
    - "{{requestfile2}}"

  - name: consume ws 
    uri: 
      url: "{{uribcu}}"
      method: POST
      return_content: yes
      headers:
        Content-Type: "text/xml;charset=UTF-8"
        SOAPAction: "wsbcucotizaciones.Execute"
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    with_items:
    - { src: "{{requestfile1}}", dest: "{{cotfile1}}" }
    - { src: "{{requestfile2}}", dest: "{{cotfile2}}" }   

- hosts: sapserver
  gather_facts: no
  vars_files:
    - ./vars.yml
  tasks:       
  - name: Copiar archivos descargados
    win_copy:
      src: "{{item}}"
      dest: "{{path_server}}"
    with_items:
    - "{{cotfile1}}"
    - "{{cotfile2}}"
